In [ ]:
import numpy as np
import matplotlib.pyplot as plt

a = np.arange(0,10,1).reshape(2,5)
a[1] = a[1][::-1]
a.T

In [ ]:
# array reverse
a = np.arange(0,10,1)
a = a[::-1]

# sort array
x = np.sort(a)
# a not sorted x is sorted copy of a
print(a)
# x = a.sort()
x

In [ ]:
a = np.array([1,7,2,8,3])
b = np.array([2,9,8,6,9])


np.vstack((a,b)).T.ravel()


In [98]:
a = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]])
# b = a[1::2]
# c = a[0::2]
# b=b.T.ravel()
# c=c.T.ravel()
np.concatenate((a[::2].T.ravel(),a[1::2].T.ravel()))

#alternate solution
# np.vstack((a[::2], a[1::2])).T.flatten()

array([ 1,  9,  2, 10,  3, 11,  4, 12,  5, 13,  6, 14,  7, 15,  8, 16])

In [92]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

np.hstack((A,B)).reshape(6,3)

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6],
       [13, 14, 15],
       [ 7,  8,  9],
       [16, 17, 18]])

In [ ]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
)
np.rot90(a, -1) #-1 indicates clockwise rotation


In [ ]:
a = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]]
)
a.T.ravel()

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b =np.array([10,11,12])
a+b

In [ ]:
a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
)
np.triu(a) #upper triangle
np.tril(a) #lower triangle

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

np.block([[A,np.zeros((2,2))],[np.zeros((2,2)),B]])

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.pad(A, pad_width=1, mode='constant', constant_values=0)

In [ ]:
image = np.arange(10000)

image_reshaped = image.reshape(100, 100)

plt.imshow(image_reshaped, cmap='gray')
plt.show()

In [85]:
a = np.array([1, 3, 2, 4, 6, 5, 7])

peaks = np.where((a[1:-1] > a[:-2]) & (a[1:-1] > a[2:]))[0] + 1
peaks = np.concatenate((peaks, [len(a)-1])) 
print(peaks)

[1 4 6]


In [100]:
y_actual = np.array([1.3, 2.5, 3.8, 4.7, 5.1])
y_predicted = np.array([1.12, 2.3, 2.9, 4.5, 5.0])
m = len(y_actual)

error = -1/m * np.sum(y_actual * np.log(y_predicted))
error

np.float64(-4.310559603414099)

In [101]:
#softmax function
x = np.array([1, 2, 3, 4, 1, 6, 7, 8, 9, 10])
np.exp(x) / np.sum(np.exp(x))

array([7.83409892e-05, 2.12952887e-04, 5.78865964e-04, 1.57352083e-03,
       7.83409892e-05, 1.16268337e-02, 3.16050107e-02, 8.59113264e-02,
       2.33531197e-01, 6.34803610e-01])

In [106]:
y_actual = np.array([1.3, 2.5, 3.8, 4.7, 5.1])
y_predicted = np.array([1.12, 2.3, 2.9, 4.5, 5.0])
n = len(y_actual)

error = 1/n * np.sum(np.square(y_predicted - y_actual))
print(str(error*100)+ "%")
# error in 3 point precision
print("{:.3f}".format(error*100)+ "%")

18.647999999999996%
18.648%
